### ISSUE TITLE
Datapack validating failed! [1.18.1]

### ISSUE THREAD

**Issue by xR4YM0ND** [globalista-dev/Fabric-Reinforced-Obsidian-Addon#1]
Can't load into a existing world or create a new world either...

https://gist.github.com/SpigotDE/d81b9733ac57651350742d12b5ee3914

**Comment by xR4YM0ND** [comment]
Without the mod it works

**Comment by globalista-dev** [comment]
I couldn't exactly reproduce this error: I got a similar one on my log, but I could load and create worlds. However, I think it was caused by Not Enough Crashes not liking that I replaced a recipe with a blank one.

Should be fixed on the latest version (1.18.1-1.1.1)

**Comment by xR4YM0ND** [comment]
OK thx i will Test it

**Comment by globalista-dev** [comment]
It's not up on Curse Forge yet, but you can download it from GitHub

**Comment by xR4YM0ND** [comment]
Works fine , worlds load up <3
